# Generated by Django 3.2.7 on 2021-09-10 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='attendance',
        ),
        migrations.AddField(
            model_name='attendance',
            name='schedule',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='onlineclass.schedule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='type',
            field=models.BooleanField(null=True),
        ),
    ]
