# Generated by Django 3.2.7 on 2021-09-10 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclass', '0004_auto_20210910_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='schedule',
            new_name='log',
        ),
    ]
