# Generated by Django 3.2.7 on 2021-09-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclass', '0006_rename_log_attendance_classid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='active_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='A', max_length=1, null=True),
        ),
    ]
