# Generated by Django 3.2.7 on 2021-09-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclass', '0008_remove_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='active_time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='type',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
